### ISSUE TITLE
What is the "Testing" dependency in the test target?

### ISSUE THREAD

**Issue by factotvm** [VaporExamplesLab/ServerSideSwift_J_RelationsAwt#1]
I've scoured the web looking for good examples of how to set up an executable with tests in a good way using Swift Package Manager. This seems to be a great example, but I can't figure out what the "Testing" dependency is in your "AppTests" test target. Could you enlighten me? Thanks!

**Comment by marc-medley** [comment]
@factotvm "Testing" is a particular part of the `vapor` package dependency.
 
see:  https://github.com/vapor/vapor/tree/master/Sources/Testing

``` swift
dependencies: [
  .package(url: "https://github.com/vapor/vapor.git", .upToNextMajor(from: "2.2.2")),
  //…
],
targets: [
  //…
  .testTarget(name: "AppTests", dependencies: ["App", "Testing"])
]
```

**Comment by factotvm** [comment]
Thanks so much!
